# configs/defaults/account.yaml
# デフォルトのアカウント設定

genre: 'renai' # 恋愛・人間関係
locale: 'ja-JP'
posting:
  time_window: ['09:00', '11:00']
  days: [Mon, Tue, Wed, Thu, Fri]
ai:
  provider: 'openrouter'
  model: 'deepseek/deepseek-chat-v3.1:free'
  temperature: 0.7
  max_tokens: 1200
note:
  login_method: 'email_password'
  cookie_secret_name: 'NOTE_COOKIE'
sheets:
  enabled: true
  doc_id: ''
  worksheet: 'posts'
overrides:
  seasonal_topic: '恋愛・人間関係'
  tags:
    [
      '#人間関係',
      '#メンタル',
      '#自己肯定感',
      '#引き寄せ',
      '#引き寄せの法則',
      '#裏技',
      '#PR',
    ]
