name: followFromArticles

on:
  # 実行時間が長くなってしまうのと、検索結果からフォローするほうが効率的と思われるため、コメントアウト

  # フォロー制限予想 １回につき１５回で、１日のフォロー制限は１００人
  schedule:
    # - cron: '45 2 * * *'   # 毎日11:50(JST)に実行

    - cron: '0 0 * * *' # 毎日9:00(JST)

    - cron: '15 1 * * *' # JST 10:15 一時的に追加

    - cron: '0 3 * * *' # 毎日12:00(JST)
    - cron: '0 6 * * *' # 毎日15:00(JST)
    - cron: '0 9 * * *' # 毎日18:00(JST)
    - cron: '0 12 * * *' # 毎日21:00(JST)
    - cron: '0 15 * * *' # 毎日0:00(JST)
    - cron: '0 18 * * *' # 毎日3:00(JST)
    - cron: '0 21 * * *' # 毎日6:00(JST)
  workflow_dispatch:

jobs:
  follow-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout note-auto-core
        uses: actions/checkout@v4
        with:
          repository: aa-0921/note-auto-core
          path: note-auto-core
          ref: main
          token: ${{ secrets.CORE_REPO_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          # note-auto-coreの依存関係をインストール
          cd note-auto-core && npm install
          cd ..
          # ローカルパッケージを直接参照してインストール
          npm install ./note-auto-core
      - name: Run follow/followFromArticles.js
        env:
          NOTE_EMAIL: ${{ secrets.NOTE_EMAIL }}
          NOTE_PASSWORD: ${{ secrets.NOTE_PASSWORD }}
        run: node scripts/followFromArticles.js
